### ISSUE TITLE
Access denied finding property "camera.aux.packagelist"

### ISSUE THREAD

**Issue by nickolight** [caseyryan/flutter_jumio#9]
Should we add some permissions for the camera in Android?

**Comment by caseyryan** [comment]
No, it's not required. The error says that you have an incomparable Android sdk. Make sure you build with a version 29

**Comment by nickolight** [comment]
I built the code from the example where 'targetSdkVersion' already set to 29

**Comment by caseyryan** [comment]
Your local sdk must also be compatible, please double check it. The example is 100% working, I tested it.

**Comment by nickolight** [comment]
What do you mean with local SDK?
Btw, what version of flutter did you use for the test code from example?

P.S. I can build and run the app successfully but when I click any type of identity it through the error: Access denied finding property "camera.aux.packagelist"

**Comment by caseyryan** [comment]
I mean the Android sdk that you have installed on your computer. If it's no the latest, upgrade it. You can also try to add a camera permission, just to check if it's not the reason for the error (I tested it without it, and it worked. But who knows). 
As to flutter. It was first built with flutter 1.12.5. But now I have 1.20.2 installed and this plugin works fine. We use it in a Migom bank mobile app

**Comment by nickolight** [comment]
What about iOS? When I click "Init Document Verification" Xcode through:
`flutter: [Flutter Jumio Native Side Message] {onError: {errorMessage: Cancelled with exception DocumentVerificationInvalidConfigurationException: Mandatory parameter (country) is not properly set!}}`

**Comment by caseyryan** [comment]
I'm not sure about document verification. I don't have a token for it, so I can't test if it works or not. I only have access to netverify. My plugin is just a port of jumio official Cordova plugin to flutter. So if they have this part broken, mine won't be working as well. 
But maybe I just missed the country parameter in my example project initialization. Take a look at that code

**Comment by JumioMobileTeam** [comment]
Hi @caseyryan,
Thank you for all your efforts on this open-source plugin. 
We've just released our official plugin today which will also be maintained upon new Jumio Android & iOS SDK releases.
Check it out here - https://github.com/Jumio/mobile-flutter
It also contains support for DocumentVerification of course.

**Comment by caseyryan** [comment]
> Hi @caseyryan,
> Thank you for all your efforts on this open-source plugin.
> We've just released our official plugin today which will also be maintained upon new Jumio Android & iOS SDK releases.
> Check it out here - https://github.com/Jumio/mobile-flutter
> It also contains support for DocumentVerification of course.

Great! Thank you
